### ISSUE TITLE
Gitlab-pages: Pages.conf file not copied in the image

### ISSUE THREAD

**Issue by gaelbro** [genshen/docker-gitlab#5]
Hi,

You provide the pages.conf file beside the Dockerfile for gitlab-pages, but I don't see this file being copied in the Dockerfile. Why is that ?
Thanks for your help.

**Comment by genshen** [comment]
In gitlab pages, the path of config file can be specified in command line in docker container.
(e.g. `docker run -v ${PWD}/config:/etc/gitlab genshen/gitlab-pages ./bin/gitlab-pages -config /etc/gitlab/pages.conf`).
You can put your `pages.conf` file in host directory `${PWD}/config` and mount into docker container via `-v`, then the config file can be read by gitlab-pages in docker container.
